[project]
name = "micromax"
authors = [
    { name = "MicroMax", email = "dev@example.com" },
]
description = "MicroMax Import/Export customization for ERPNext (LC Proforma, Export/Import Shipment, Cost Sheet, Packing)."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "beautifulsoup4",
    "lxml",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"